DewfordManor_1F_MapScripts::
	map_script MAP_SCRIPT_ON_TRANSITION, DewfordManor_1F_OnTransition
	.byte 0

DewfordManor_1F_OnTransition:
	setflag FLAG_LANDMARK_DEWFORD_MANOR
	end

DewfordManor_1F_EventScript_AGATHA_2:: @ 81EC1B3
	trainerbattle_single TRAINER_AGATHA_2, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

DewfordManor_1F_EventScript_GREEN_2:: @ 81EC1B3
	trainerbattle_single TRAINER_GREEN_2, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

DewfordManor_1F_EventScript_SABRINA_2:: @ 81EC1B3
	trainerbattle_single TRAINER_SABRINA_2, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

DewfordManor_1F_EventScript_MORTY_2:: @ 81EC1B3
	trainerbattle_single TRAINER_MORTY_2, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

DewfordManor_1F_EventScript_LI_2:: @ 81EC1B3
	trainerbattle_single TRAINER_LI_2, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

DewfordManor_1F_EventScript_SPENCER_2:: @ 81EC1B3
	trainerbattle_single TRAINER_SPENCER_2, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

DewfordManor_1F_EventScript_NOLAND_2:: @ 81EC1B3
	trainerbattle_single TRAINER_NOLAND_2, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

DewfordManor_1F_EventScript_GALACTIC_1:: @ 81EC1B3
	trainerbattle_single TRAINER_GALACTIC_1, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

DewfordManor_1F_EventScript_GALACTIC_2:: @ 81EC1B3
	trainerbattle_single TRAINER_GALACTIC_2, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

DewfordManor_1F_EventScript_GALACTIC_3:: @ 81EC1B3
	trainerbattle_single TRAINER_GALACTIC_3, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

DewfordManor_1F_EventScript_GALACTIC_4:: @ 81EC1B3
	trainerbattle_single TRAINER_GALACTIC_4, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

DewfordManor_1F_EventScript_GALACTIC_5:: @ 81EC1B3
	trainerbattle_single TRAINER_GALACTIC_5, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

DewfordManor_1F_EventScript_GALACTIC_6:: @ 81EC1B3
	trainerbattle_single TRAINER_GALACTIC_6, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

DewfordManor_1F_EventScript_GALACTIC_7:: @ 81EC1B3
	trainerbattle_single TRAINER_GALACTIC_7, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

DewfordManor_1F_EventScript_GALACTIC_8:: @ 81EC1B3
	trainerbattle_single TRAINER_GALACTIC_8, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

DewfordManor_1F_EventScript_GALACTIC_9:: @ 81EC1B3
	trainerbattle_single TRAINER_GALACTIC_9, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

DewfordManor_1F_EventScript_GALACTIC_10:: @ 81EC1B3
	trainerbattle_single TRAINER_GALACTIC_10, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

DewfordManor_1F_EventScript_GALACTIC_11:: @ 81EC1B3
	trainerbattle_single TRAINER_GALACTIC_11, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

DewfordManor_1F_EventScript_GALACTIC_12:: @ 81EC1B3
	trainerbattle_single TRAINER_GALACTIC_12, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

DewfordManor_1F_EventScript_GALACTIC_13:: @ 81EC1B3
	trainerbattle_single TRAINER_GALACTIC_13, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

DewfordManor_1F_EventScript_GALACTIC_14:: @ 81EC1B3
	trainerbattle_single TRAINER_GALACTIC_14, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

DewfordManor_1F_EventScript_GALACTIC_15:: @ 81EC1B3
	trainerbattle_single TRAINER_GALACTIC_15, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

DewfordManor_1F_EventScript_GALACTIC_16:: @ 81EC1B3
	trainerbattle_single TRAINER_GALACTIC_16, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

DewfordManor_1F_EventScript_GALACTIC_17:: @ 81EC1B3
	trainerbattle_single TRAINER_GALACTIC_17, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

DewfordManor_1F_EventScript_GALACTIC_18:: @ 81EC1B3
	trainerbattle_single TRAINER_GALACTIC_18, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

DewfordManor_1F_EventScript_GALACTIC_19:: @ 81EC1B3
	trainerbattle_single TRAINER_GALACTIC_19, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

DewfordManor_1F_EventScript_GALACTIC_20:: @ 81EC1B3
	trainerbattle_single TRAINER_GALACTIC_20, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

DewfordManor_1F_EventScript_GALACTIC_21:: @ 81EC1B3
	trainerbattle_single TRAINER_GALACTIC_21, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

DewfordManor_1F_EventScript_GALACTIC_22:: @ 81EC1B3
	trainerbattle_single TRAINER_GALACTIC_22, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

DewfordManor_1F_EventScript_GALACTIC_23:: @ 81EC1B3
	trainerbattle_single TRAINER_GALACTIC_23, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

DewfordManor_1F_EventScript_GALACTIC_24:: @ 81EC1B3
	trainerbattle_single TRAINER_GALACTIC_24, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

DewfordManor_1F_EventScript_GALACTIC_25:: @ 81EC1B3
	trainerbattle_single TRAINER_GALACTIC_25, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end
