DeepWood_MapScripts::
	.byte 0

DeepWood_EventScript_RICHBOY_1:: @ 81EC1B3
	trainerbattle_single TRAINER_RICHBOY_1, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

DeepWood_EventScript_SCHOOLKIDF_1:: @ 81EC1B3
	trainerbattle_single TRAINER_SCHOOLKIDF_1, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

DeepWood_EventScript_SCHOOLKIDM_1:: @ 81EC1B3
	trainerbattle_single TRAINER_SCHOOLKIDM_1, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end