GraniteCave_B2F_MapScripts::
	map_script MAP_SCRIPT_ON_RESUME, GraniteCave_B2F_SetFlashRadius
	.byte 0

GraniteCave_B2F_SetFlashRadius:
	setflashradius 4
	end

GraniteCave_B2F_EventScript_COOLT2_2:: @ 81EC1B3
	trainerbattle_single TRAINER_COOLT2_2, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

GraniteCave_B2F_EventScript_COOLT9_2:: @ 81EC1B3
	trainerbattle_single TRAINER_COOLT9_2, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

GraniteCave_B2F_EventScript_JUAN_2A:: @ 81EC1B3
	trainerbattle_single TRAINER_JUAN_2A, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

GraniteCave_B2F_EventScript_WALACE_2:: @ 81EC1B3
	trainerbattle_single TRAINER_WALACE_2, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

GraniteCave_B2F_EventScript_WINONA_2A:: @ 81EC1B3
	trainerbattle_single TRAINER_WINONA_2A, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

GraniteCave_B2F_EventScript_RANGER7_2:: @ 81EC1B3
	trainerbattle_single TRAINER_RANGER7_2, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

GraniteCave_B2F_EventScript_COOLT15_2:: @ 81EC1B3
	trainerbattle_single TRAINER_COOLT15_2, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

GraniteCave_B2F_EventScript_BRUNO_2:: @ 81EC1B3
	trainerbattle_single TRAINER_BRUNO_2, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

GraniteCave_B2F_EventScript_BRAWLY_2A:: @ 81EC1B3
	trainerbattle_single TRAINER_BRAWLY_2A, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

GraniteCave_B2F_EventScript_SHADY_2:: @ 81EC1B3
	trainerbattle_single TRAINER_SHADY_2, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

GraniteCave_B2F_EventScript_COURTNEY_2A:: @ 81EC1B3
	trainerbattle_single TRAINER_COURTNEY_2A, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

GraniteCave_B2F_EventScript_BRANDON_2:: @ 81EC1B3
	trainerbattle_single TRAINER_BRANDON_2, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

GraniteCave_B2F_EventScript_MAXIE_2:: @ 81EC1B3
	trainerbattle_single TRAINER_MAXIE_2, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

GraniteCave_B2F_EventScript_MAGMA_104:: @ 81EC1B3
	trainerbattle_single TRAINER_MAGMA_104, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

GraniteCave_B2F_EventScript_MAGMA_105:: @ 81EC1B3
	trainerbattle_single TRAINER_MAGMA_105, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

GraniteCave_B2F_EventScript_COOLTRAINERF_2:: @ 81EC1B3
	trainerbattle_single TRAINER_COOLTRAINERF_2, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

GraniteCave_B2F_EventScript_DRAGONTAMER_2:: @ 81EC1B3
	trainerbattle_single TRAINER_DRAGONTAMER_2, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

GraniteCave_B2F_EventScript_OLDCOUPLE_2:: @ 81EC1B3
	trainerbattle_single TRAINER_OLDCOUPLE_2, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

GraniteCave_B2F_EventScript_PSYCHICF_2:: @ 81EC1B3
	trainerbattle_single TRAINER_PSYCHICF_2, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

GraniteCave_B2F_EventScript_ROCKET_1:: @ 81EC1B3
	trainerbattle_single TRAINER_ROCKET_1, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

GraniteCave_B2F_EventScript_ROCKET_2:: @ 81EC1B3
	trainerbattle_single TRAINER_ROCKET_2, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

GraniteCave_B2F_EventScript_ROCKET_3:: @ 81EC1B3
	trainerbattle_single TRAINER_ROCKET_3, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

GraniteCave_B2F_EventScript_ROCKET_4:: @ 81EC1B3
	trainerbattle_single TRAINER_ROCKET_4, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

GraniteCave_B2F_EventScript_ROCKET_5:: @ 81EC1B3
	trainerbattle_single TRAINER_ROCKET_5, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

GraniteCave_B2F_EventScript_ROCKET_6:: @ 81EC1B3
	trainerbattle_single TRAINER_ROCKET_6, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

GraniteCave_B2F_EventScript_ROCKET_7:: @ 81EC1B3
	trainerbattle_single TRAINER_ROCKET_7, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

GraniteCave_B2F_EventScript_ROCKET_8:: @ 81EC1B3
	trainerbattle_single TRAINER_ROCKET_8, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

GraniteCave_B2F_EventScript_ROCKET_9:: @ 81EC1B3
	trainerbattle_single TRAINER_ROCKET_9, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

GraniteCave_B2F_EventScript_ROCKET_10:: @ 81EC1B3
	trainerbattle_single TRAINER_ROCKET_10, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

GraniteCave_B2F_EventScript_ROCKET_11:: @ 81EC1B3
	trainerbattle_single TRAINER_ROCKET_11, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

GraniteCave_B2F_EventScript_ROCKET_12:: @ 81EC1B3
	trainerbattle_single TRAINER_ROCKET_12, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

GraniteCave_B2F_EventScript_ROCKET_13:: @ 81EC1B3
	trainerbattle_single TRAINER_ROCKET_13, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

GraniteCave_B2F_EventScript_ROCKET_14:: @ 81EC1B3
	trainerbattle_single TRAINER_ROCKET_14, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

GraniteCave_B2F_EventScript_ROCKET_15:: @ 81EC1B3
	trainerbattle_single TRAINER_ROCKET_15, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

GraniteCave_B2F_EventScript_ROCKET_16:: @ 81EC1B3
	trainerbattle_single TRAINER_ROCKET_16, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

GraniteCave_B2F_EventScript_ROCKET_17:: @ 81EC1B3
	trainerbattle_single TRAINER_ROCKET_17, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

GraniteCave_B2F_EventScript_ROCKET_18:: @ 81EC1B3
	trainerbattle_single TRAINER_ROCKET_18, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

GraniteCave_B2F_EventScript_ROCKET_19:: @ 81EC1B3
	trainerbattle_single TRAINER_ROCKET_19, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

GraniteCave_B2F_EventScript_ROCKET_20:: @ 81EC1B3
	trainerbattle_single TRAINER_ROCKET_20, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

GraniteCave_B2F_EventScript_ROCKET_21:: @ 81EC1B3
	trainerbattle_single TRAINER_ROCKET_21, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

GraniteCave_B2F_EventScript_ROCKET_22:: @ 81EC1B3
	trainerbattle_single TRAINER_ROCKET_22, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

GraniteCave_B2F_EventScript_ROCKET_23:: @ 81EC1B3
	trainerbattle_single TRAINER_ROCKET_23, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

GraniteCave_B2F_EventScript_ROCKET_24:: @ 81EC1B3
	trainerbattle_single TRAINER_ROCKET_24, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

GraniteCave_B2F_EventScript_ROCKET_25:: @ 81EC1B3
	trainerbattle_single TRAINER_ROCKET_25, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end