SlateportCity_House_MapScripts:: @ 820D9AE
	.byte 0

SlateportCity_House_EventScript_PokefanM:: @ 820D9AF
	msgbox SlateportCity_House_Text_NatureToDoWithStatGains, MSGBOX_NPC
	end

SlateportCity_House_EventScript_Girl:: @ 820D9B8
	msgbox SlateportCity_House_Text_MustBeGoingToBattleTent, MSGBOX_NPC
	end

SlateportCity_House_Text_NatureToDoWithStatGains: @ 820D9C1
	.string "My Pokémon has a Hasty nature.\p"
	.string "It has higher Speed compared to\n"
	.string "my other Pokémon.\p"
	.string "Maybe their nature has something to\n"
	.string "do with the stat gains of Pokémon.$"

SlateportCity_House_Text_MustBeGoingToBattleTent: @ 820DA59
	.string "You're a Trainer, aren't you?\p"
	.string "Since you came to Slateport City,\n"
	.string "you must be going to the Battle Tent.$"

SlateportCity_House_EventScript_AQUA_1:: @ 81EC1B3
	trainerbattle_single TRAINER_AQUA_1, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

SlateportCity_House_EventScript_AQUA_2:: @ 81EC1B3
	trainerbattle_single TRAINER_AQUA_2, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

SlateportCity_House_EventScript_AQUA_3:: @ 81EC1B3
	trainerbattle_single TRAINER_AQUA_3, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

SlateportCity_House_EventScript_AQUA_4:: @ 81EC1B3
	trainerbattle_single TRAINER_AQUA_4, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

SlateportCity_House_EventScript_AQUA_5:: @ 81EC1B3
	trainerbattle_single TRAINER_AQUA_5, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

SlateportCity_House_EventScript_AQUA_6:: @ 81EC1B3
	trainerbattle_single TRAINER_AQUA_6, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

SlateportCity_House_EventScript_AQUA_7:: @ 81EC1B3
	trainerbattle_single TRAINER_AQUA_7, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

SlateportCity_House_EventScript_AQUA_8:: @ 81EC1B3
	trainerbattle_single TRAINER_AQUA_8, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

SlateportCity_House_EventScript_AQUA_9:: @ 81EC1B3
	trainerbattle_single TRAINER_AQUA_9, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

SlateportCity_House_EventScript_AQUA_10:: @ 81EC1B3
	trainerbattle_single TRAINER_AQUA_10, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

SlateportCity_House_EventScript_AQUA_11:: @ 81EC1B3
	trainerbattle_single TRAINER_AQUA_11, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

SlateportCity_House_EventScript_AQUA_12:: @ 81EC1B3
	trainerbattle_single TRAINER_AQUA_12, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

SlateportCity_House_EventScript_AQUA_13:: @ 81EC1B3
	trainerbattle_single TRAINER_AQUA_13, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

SlateportCity_House_EventScript_AQUA_14:: @ 81EC1B3
	trainerbattle_single TRAINER_AQUA_14, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

SlateportCity_House_EventScript_AQUA_15:: @ 81EC1B3
	trainerbattle_single TRAINER_AQUA_15, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

SlateportCity_House_EventScript_AQUA_16:: @ 81EC1B3
	trainerbattle_single TRAINER_AQUA_16, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

SlateportCity_House_EventScript_AQUA_17:: @ 81EC1B3
	trainerbattle_single TRAINER_AQUA_17, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

SlateportCity_House_EventScript_AQUA_18:: @ 81EC1B3
	trainerbattle_single TRAINER_AQUA_18, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

SlateportCity_House_EventScript_AQUA_19:: @ 81EC1B3
	trainerbattle_single TRAINER_AQUA_19, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

SlateportCity_House_EventScript_AQUA_20:: @ 81EC1B3
	trainerbattle_single TRAINER_AQUA_20, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

SlateportCity_House_EventScript_AQUA_21:: @ 81EC1B3
	trainerbattle_single TRAINER_AQUA_21, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

SlateportCity_House_EventScript_AQUA_22:: @ 81EC1B3
	trainerbattle_single TRAINER_AQUA_22, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

SlateportCity_House_EventScript_AQUA_23:: @ 81EC1B3
	trainerbattle_single TRAINER_AQUA_23, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

SlateportCity_House_EventScript_AQUA_24:: @ 81EC1B3
	trainerbattle_single TRAINER_AQUA_24, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

SlateportCity_House_EventScript_AQUA_25:: @ 81EC1B3
	trainerbattle_single TRAINER_AQUA_25, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

SlateportCity_House_EventScript_SHELLY_2A:: @ 81EC1B3
	trainerbattle_single TRAINER_SHELLY_2A, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

SlateportCity_House_EventScript_MATT_2A:: @ 81EC1B3
	trainerbattle_single TRAINER_MATT_2A, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

SlateportCity_House_EventScript_ARCHIE_2:: @ 81EC1B3
	trainerbattle_single TRAINER_ARCHIE_2, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end
