SandstrewnRuins_B1F_MapScripts::
	.byte 0

SandstrewnRuins_B1F_EventScript_CYRUS_5:: @ 81EC1B3
	trainerbattle_single TRAINER_CYRUS_5, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

SandstrewnRuins_B1F_EventScript_GALACTIC_113:: @ 81EC1B3
	trainerbattle_single TRAINER_GALACTIC_113, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

SandstrewnRuins_B1F_EventScript_GALACTIC_114:: @ 81EC1B3
	trainerbattle_single TRAINER_GALACTIC_114, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

SandstrewnRuins_B1F_EventScript_GALACTIC_115:: @ 81EC1B3
	trainerbattle_single TRAINER_GALACTIC_115, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

SandstrewnRuins_B1F_EventScript_GIOVANNI_5:: @ 81EC1B3
	trainerbattle_single TRAINER_GIOVANNI_5, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

SandstrewnRuins_B1F_EventScript_ROCKET_113:: @ 81EC1B3
	trainerbattle_single TRAINER_ROCKET_113, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

SandstrewnRuins_B1F_EventScript_ROCKET_114:: @ 81EC1B3
	trainerbattle_single TRAINER_ROCKET_114, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

SandstrewnRuins_B1F_EventScript_ROCKET_115:: @ 81EC1B3
	trainerbattle_single TRAINER_ROCKET_115, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end