Route111_RuinsExterior_MapScripts::
	.byte 0

Route111_RuinsExterior_EventScript_ARCH_5:: @ 81EC1B3
	trainerbattle_single TRAINER_ARCH_5, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

Route111_RuinsExterior_EventScript_BRANDON_5:: @ 81EC1B3
	trainerbattle_single TRAINER_BRANDON_5, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

Route111_RuinsExterior_EventScript_LUCY_5:: @ 81EC1B3
	trainerbattle_single TRAINER_LUCY_5, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end

Route111_RuinsExterior_EventScript_GEM_5:: @ 81EC1B3
	trainerbattle_single TRAINER_GEM_5, Route102_Text_GENIntro, Route102_Text_GENDefeat
	msgbox Route102_Text_GENPostBattle, MSGBOX_AUTOCLOSE
	end